### PR TITLE
Fix spice.h include file

### PR DESCRIPTION
**Pull request by hardening**
Added guards for multiple inclusions and for C++ projects.

### CODE REVIEW

**Comment by gnif** [comment]
Awesome, thanks for this!
I am curious now what project (if any) this is being used in?

**Comment by hardening** [comment]
None for now, I was just curious to know how was handled screen resolutions in LookingGlass, so I gave a look at what was transported over spice. As display channel is not supported I guess that screen dimensions changes can only be initiated by the guest, not by the host...

**Comment by hardening** [comment]
My final goal was to see how to handle multiple monitors in LookingGlass...

**Comment by gnif** [comment]
PureSpice doesn't handle any of that, it's simply an input library. Multiple monitor support for LG would require major changes to the host application to allow for multiple monitor capture and streaming into shared memory. In theory, it's possible, but the bandwidth requirements will likely be far too high to be of much use since we are CPU memory copy bound in several places.

I have been working on improving this with the `ADL` project by implementing the ability to use a UDMABUF to avoid extra client-side copies, but this library is far from ready to use.

**Pull request merged**
